version: '3.1'

services:

  db_cadastro:
    container_name: db-cadastro
    image: postgres
    volumes:
      - data-postgres:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=banco123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=parking-control-db
    ports:
      - "5432:5432"
    networks:
      - rede

volumes:
  data-postgres:

networks:
  rede:
